local builtin = require('telescope.builtin')
vip.keymap.set('n', '<leader>ff', builtin.find_files, {})
vip.keymap.set('n', '<C-p>', builtin.git_files, {})
vip.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vip.fn.input("Grep > ") })
end, {})
vip.keymap.set('n', '<leader>sw', builtin.grep_string, {})
vip.keymap.set('n', '<leader>sg', builtin.live_grep, {})
